name: 'team-membership'
description: 'Get a user team membership in an organization'
branding:
  icon: 'at-sign'
  color: 'blue'
inputs:
  organization:
    description: 'Organization name (default is repo owner)'
    required: false
    default:  ${{ github.repository_owner }}
  username:
    description: 'Username to get teams or check team membership'
    required: true
  team:
    description: 'Team to check the membership'
    required: true
  GITHUB_TOKEN:
    description: 'GITHUB_TOKEN'
    required: true

outputs:
  isTeamMember:
    description: 'Is the user a member of the team'
runs:
  using: 'node16'
  main: 'dist/index.js'
